# Generated by Django 5.2.11 on 2026-02-26 13:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.models.ads


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название объявления')),
                ('place', models.CharField(choices=[('site', 'Сайт'), ('mobile_app', 'Мобильное приложение'), ('store_screen', 'Экран в магазине')], max_length=20, verbose_name='Место размежения')),
                ('url', models.URLField(verbose_name='Url рекламного объекта')),
                ('description', models.TextField(verbose_name='Текст объявления')),
            ],
            options={
                'verbose_name': 'Рекламное объявление',
                'verbose_name_plural': 'Рекламные объявления',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(max_length=255, unique=True, verbose_name='Внешний сквозной идентификатор')),
                ('width', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20000)], verbose_name='Ширина')),
                ('height', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20000)], verbose_name='Высота')),
                ('file', models.FileField(upload_to=core.models.ads.banner_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gif', 'png', 'jpg', 'jpeg', 'htm', 'html'])], verbose_name='Файл с рекламными материалами')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Статус')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='core.advertisement', verbose_name='')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название кампании')),
                ('start_date', models.DateField(db_index=True, verbose_name='Дата старта')),
                ('end_date', models.DateField(db_index=True, verbose_name='Дата завершения')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Бюджет')),
                ('strategy', models.CharField(choices=[('max_impressions', 'Максимальные показы'), ('evenly', 'Равномерное распределение бюджета')], max_length=31, verbose_name='Стратегия трат')),
                ('max_impressions_per_day', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)], verbose_name='максимальное число показов в день')),
                ('targeting', models.JSONField(blank=True, default=dict, verbose_name='Таргетинг')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Рекламная кампания',
                'verbose_name_plural': 'Рекламные кампании',
            },
        ),
        migrations.AddField(
            model_name='advertisement',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='core.campaign'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(condition=models.Q(('budget__gte', 0)), name='budget_positive'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('max_impressions_per_day__isnull', False), ('strategy', 'max_impressions')), models.Q(('max_impressions_per_day__isnull', True), ('strategy', 'evenly')), _connector='OR'), name='strategy_impressions_constraint'),
        ),
    ]
