# Generated by Django 5.2.11 on 2026-02-26 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_advertisement_banner_campaign_advertisement_campaign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='core.campaign', verbose_name='Кампания'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='core.advertisement', verbose_name='Объявление'),
        ),
    ]
